name: Validate Entity ID PR

on: pull_request

jobs:
  validate_entity_file_name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - run: pip3 install -r .github/scripts/python/requirements.txt

      - name: Validate the entity id name during a pull request
        run: python3 .github/scripts/python/validate_pr_file_name.py
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: github.event_name == 'pull_request'
